# Generated by Django 3.2.13 on 2022-05-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Another'), (2, 'Puzzle - Escape Room '), (1, 'Gears'), (3, 'Carver')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(default='')),
                ('price', models.PositiveSmallIntegerField()),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop_app.category')),
            ],
        ),
    ]
