# Generated by Django 3.2.13 on 2022-05-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[(0, 'Another'), (3, 'Carver'), (2, 'Puzzle - Escape Room '), (1, 'Gears')], default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.category'),
        ),
    ]
